/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as SocialSecurityRouteImport } from './routes/social-security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProjectionsRouteImport } from './routes/projections'
import { Route as PaycheckRouteImport } from './routes/paycheck'
import { Route as MuniBondsRouteImport } from './routes/muni-bonds'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DebtsRouteImport } from './routes/debts'
import { Route as DbRouteImport } from './routes/db'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as IndexRouteImport } from './routes/index'

const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialSecurityRoute = SocialSecurityRouteImport.update({
  id: '/social-security',
  path: '/social-security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectionsRoute = ProjectionsRouteImport.update({
  id: '/projections',
  path: '/projections',
  getParentRoute: () => rootRouteImport,
} as any)
const PaycheckRoute = PaycheckRouteImport.update({
  id: '/paycheck',
  path: '/paycheck',
  getParentRoute: () => rootRouteImport,
} as any)
const MuniBondsRoute = MuniBondsRouteImport.update({
  id: '/muni-bonds',
  path: '/muni-bonds',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsRoute = DebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => rootRouteImport,
} as any)
const DbRoute = DbRouteImport.update({
  id: '/db',
  path: '/db',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/artifacts': typeof ArtifactsRoute
  '/db': typeof DbRoute
  '/debts': typeof DebtsRoute
  '/expenses': typeof ExpensesRoute
  '/goals': typeof GoalsRoute
  '/guide': typeof GuideRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/muni-bonds': typeof MuniBondsRoute
  '/paycheck': typeof PaycheckRoute
  '/projections': typeof ProjectionsRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/social-security': typeof SocialSecurityRoute
  '/tax': typeof TaxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/artifacts': typeof ArtifactsRoute
  '/db': typeof DbRoute
  '/debts': typeof DebtsRoute
  '/expenses': typeof ExpensesRoute
  '/goals': typeof GoalsRoute
  '/guide': typeof GuideRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/muni-bonds': typeof MuniBondsRoute
  '/paycheck': typeof PaycheckRoute
  '/projections': typeof ProjectionsRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/social-security': typeof SocialSecurityRoute
  '/tax': typeof TaxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/artifacts': typeof ArtifactsRoute
  '/db': typeof DbRoute
  '/debts': typeof DebtsRoute
  '/expenses': typeof ExpensesRoute
  '/goals': typeof GoalsRoute
  '/guide': typeof GuideRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/muni-bonds': typeof MuniBondsRoute
  '/paycheck': typeof PaycheckRoute
  '/projections': typeof ProjectionsRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/social-security': typeof SocialSecurityRoute
  '/tax': typeof TaxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/artifacts'
    | '/db'
    | '/debts'
    | '/expenses'
    | '/goals'
    | '/guide'
    | '/investments'
    | '/login'
    | '/muni-bonds'
    | '/paycheck'
    | '/projections'
    | '/report'
    | '/settings'
    | '/social-security'
    | '/tax'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/artifacts'
    | '/db'
    | '/debts'
    | '/expenses'
    | '/goals'
    | '/guide'
    | '/investments'
    | '/login'
    | '/muni-bonds'
    | '/paycheck'
    | '/projections'
    | '/report'
    | '/settings'
    | '/social-security'
    | '/tax'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/artifacts'
    | '/db'
    | '/debts'
    | '/expenses'
    | '/goals'
    | '/guide'
    | '/investments'
    | '/login'
    | '/muni-bonds'
    | '/paycheck'
    | '/projections'
    | '/report'
    | '/settings'
    | '/social-security'
    | '/tax'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRoute
  ArtifactsRoute: typeof ArtifactsRoute
  DbRoute: typeof DbRoute
  DebtsRoute: typeof DebtsRoute
  ExpensesRoute: typeof ExpensesRoute
  GoalsRoute: typeof GoalsRoute
  GuideRoute: typeof GuideRoute
  InvestmentsRoute: typeof InvestmentsRoute
  LoginRoute: typeof LoginRoute
  MuniBondsRoute: typeof MuniBondsRoute
  PaycheckRoute: typeof PaycheckRoute
  ProjectionsRoute: typeof ProjectionsRoute
  ReportRoute: typeof ReportRoute
  SettingsRoute: typeof SettingsRoute
  SocialSecurityRoute: typeof SocialSecurityRoute
  TaxRoute: typeof TaxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-security': {
      id: '/social-security'
      path: '/social-security'
      fullPath: '/social-security'
      preLoaderRoute: typeof SocialSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projections': {
      id: '/projections'
      path: '/projections'
      fullPath: '/projections'
      preLoaderRoute: typeof ProjectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paycheck': {
      id: '/paycheck'
      path: '/paycheck'
      fullPath: '/paycheck'
      preLoaderRoute: typeof PaycheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muni-bonds': {
      id: '/muni-bonds'
      path: '/muni-bonds'
      fullPath: '/muni-bonds'
      preLoaderRoute: typeof MuniBondsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts': {
      id: '/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof DebtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db': {
      id: '/db'
      path: '/db'
      fullPath: '/db'
      preLoaderRoute: typeof DbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRoute,
  ArtifactsRoute: ArtifactsRoute,
  DbRoute: DbRoute,
  DebtsRoute: DebtsRoute,
  ExpensesRoute: ExpensesRoute,
  GoalsRoute: GoalsRoute,
  GuideRoute: GuideRoute,
  InvestmentsRoute: InvestmentsRoute,
  LoginRoute: LoginRoute,
  MuniBondsRoute: MuniBondsRoute,
  PaycheckRoute: PaycheckRoute,
  ProjectionsRoute: ProjectionsRoute,
  ReportRoute: ReportRoute,
  SettingsRoute: SettingsRoute,
  SocialSecurityRoute: SocialSecurityRoute,
  TaxRoute: TaxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
